version: '3.8'

services:

  api:
    build: ./backend
    container_name: mantos-api
    entrypoint: .docker/entrypoint.sh

    volumes:
      - ./backend/:/code
    ports:
      - 8000:8000
      - 3000:3000
    env_file: 
      - ./backend/.env
    networks:
      - backend-network
    depends_on:
      - mantos-api-postgres-db
    links:
      - mantos-api-postgres-db

  mantos-api-postgres-db:
    image: postgres:alpine
    container_name: mantos-api-postgres-db
    tty: true
    ports:
      - 5432:5432
    volumes: 
      - ./backend/.docker/dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=123007
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mantos_db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge